# Generated by Django 3.2.24 on 2024-02-28 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='')),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='trainer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='')),
                ('phone', models.BigIntegerField()),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('achievements', models.FileField(upload_to='')),
                ('work_experience', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='video_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer_table')),
            ],
        ),
        migrations.CreateModel(
            name='user_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('photo', models.FileField(upload_to='')),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.BigIntegerField()),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=100)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='timeschedule_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('day', models.CharField(max_length=100)),
                ('trainers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer_table')),
            ],
        ),
        migrations.CreateModel(
            name='schedule_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=100)),
                ('timeschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.timeschedule_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='rating_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('reviews', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('trainers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='order_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='order_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.order_table')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.product_table')),
            ],
        ),
        migrations.CreateModel(
            name='fee_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user_table')),
            ],
        ),
        migrations.CreateModel(
            name='attendance_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.CharField(max_length=100)),
                ('trainers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer_table')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user_table')),
            ],
        ),
    ]
