# Generated by Django 3.2.24 on 2024-02-28 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_details',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
