# Generated by Django 3.2.24 on 2024-02-28 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_order_details_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='diatchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('plan', models.TextField()),
                ('diat', models.FileField(upload_to='')),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.user_table')),
            ],
        ),
    ]
