# Generated by Django 3.2.24 on 2024-03-01 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_foodhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee_table',
            name='schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gym.schedule_booking'),
            preserve_default=False,
        ),
    ]
