# Generated by Django 3.2.24 on 2024-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_fee_table_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('food_allowed', models.TextField()),
                ('food_not_allowed', models.TextField()),
            ],
        ),
    ]
